### ISSUE TITLE
PickerItem add numberOfLines and ellipsizeMode property

### ISSUE THREAD

**Issue by AlvisSong** [Liamandrew/react-native-picky#11]
PickerItem add numberOfLines and ellipsizeMode property

**Comment by Liamandrew** [comment]
This should be trivial to add for iOS, but need to investigate how it could be possible to have the same feature on Android.
I think the configuration will be at the `Picker` level, rather than each `PickerItem`

**Comment by Liamandrew** [comment]
I have added the prop `numberOfLines` for iOS in **v0.4.0**. For now, it is only supported on iOS. Support on Android may require changing the native library being used which will need more investigation.
