### ISSUE TITLE
Multiple Picker Groups is overflowing from screen

### ISSUE THREAD

**Issue by itsramiel** [Liamandrew/react-native-picky#12]
I am trying to simulate a datetime picker , but because it is alotting the same space for every group, one of the groups is overflowing.
Is it possible to maybe assign a flex value to each GroupPicker or something similar to shrink, expand?
![rsz_1655826009762](https://user-images.githubusercontent.com/80689446/174842227-80b6465a-fb9d-4081-a17a-7d351ee18560.jpg)

**Comment by Liamandrew** [comment]
There could be a few potential solutions here. Is this only a problem on Android?

**Comment by Liamandrew** [comment]
This is more difficult than I originally thought to solve properly on Android. It might require changing the native library being used which is a bigger piece of work that will need to be investigated.

For now, in **v0.4.0** there is a new prop `width` that can be used to help with your layout a bit:

```
<Picker>
  <PickerColumn>
    <PickerItem label="Tomorrow (Wednesday)" value="1" />
    <PickerItem label="Tomorrow (Wednesday)" value="2" />
    <PickerItem label="Tomorrow (Wednesday)" value="3" />
    <PickerItem label="Tomorrow (Wednesday)" value="4" />
    <PickerItem label="Tomorrow (Wednesday)" value="5" />
  </PickerColumn>
  <PickerColumn width={60}>
    <PickerItem label="1" value="1" />
    <PickerItem label="2" value="2" />
    <PickerItem label="3" value="3" />
    <PickerItem label="4" value="4" />
    <PickerItem label="5" value="5" />
  </PickerColumn>
  <PickerColumn width={60}>
    <PickerItem label="1" value="1" />
    <PickerItem label="2" value="2" />
    <PickerItem label="3" value="3" />
    <PickerItem label="4" value="4" />
    <PickerItem label="5" value="5" />
  </PickerColumn>
</Picker>
```

![Screenshot_1657950618](https://user-images.githubusercontent.com/30114733/179342478-d9f28250-0f7d-4e72-9d4c-6123d00318bc.png)

**Comment by itsramiel** [comment]
Thank you
