### ISSUE TITLE
(iOS)PickerGroup internal Props SelectValue has no effect after being set

### ISSUE THREAD

**Issue by muyiyangyu** [Liamandrew/react-native-picky#9]
When I set selectValue to A2, the inner scroll still points to A1！
![image](https://user-images.githubusercontent.com/18657382/174517501-52d2bd7e-4144-4eb8-afca-b556242730cf.png)

I checked in iOS and setSelectedIndexes internal Data was nil, the loop didn't finish
![image](https://user-images.githubusercontent.com/18657382/174537890-22d93322-c9b0-40b2-a96a-f9596a0cb37c.png)

**Comment by Liamandrew** [comment]
Thanks for the issue @muyiyangyu 

Interestingly, the issue seems to be only when the `onChange` prop is passed.
